In [1]:
import pandas as pd

# Series

## List

In [2]:
s1 = pd.Series([1, 3, 5, None, 6, 8])
s1

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
s2 = pd.Series([1, 3, 5, None, 6, 8], 
               index=['a', 'b', 'c', 'd', 'e', 'f'])
s2

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
dtype: float64

## Dict

In [4]:
sdata = {'a': 1, 'b': 3, 'c': 5, 'd': None, 'e': 6, 'f': 8}
s3 = pd.Series(sdata)
s3

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
dtype: float64

# DataFrame

## List

In [5]:
data1 = [['Bob', 1993, 173.5],
         ['Steve', 1996, 178.1],
         ['Jeff', 1994, 183.2]]
df1 = pd.DataFrame(data1,
                   index=['I', 'II', 'III'],
                   columns=['student', 'birthyear', 'height'])
df1

    student  birthyear  height
I       Bob       1993   173.5
II    Steve       1996   178.1
III    Jeff       1994   183.2

## Dict

In [6]:
data2 = {'student': ['Bob', 'Steve', 'Jeff'],
         'birthyear': [1993, 1996, 1994],
         'height': [173.5, 178.1, 183.2]}
df2 = pd.DataFrame(data2,
                   index=['I', 'II', 'III'])
df2

    student  birthyear  height
I       Bob       1993   173.5
II    Steve       1996   178.1
III    Jeff       1994   183.2

# Read Data

In [7]:
df1= pd.read_csv('logP_dataset.csv')

In [8]:
df2 = pd.read_excel('LOL.xlsx')

# Viewing Data

In [9]:
df2.head()

     名稱  攻擊距離   魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦  類型
0   厄薩斯   175    0   0.0     0    90  580.0   3.0   345  60.0  38.0  32.1  鬥士
1    阿璃   550  418   0.8    25    92  526.0   6.5   330  53.0  20.9  30.0  法師
2   阿卡莉   125  200   0.0     0    95  575.0   8.0   345  62.4  23.0  37.0  刺客
3  亞歷斯塔   125  350   0.8    40   106  573.4   8.5   330  61.1  44.0  32.1  坦克
4   阿姆姆   125  287   0.5    40    84  613.1   9.0   335  53.4  33.0  32.1  坦克

In [10]:
df2.head(3)

    名稱  攻擊距離   魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦  類型
0  厄薩斯   175    0   0.0     0    90  580.0   3.0   345  60.0  38.0  32.1  鬥士
1   阿璃   550  418   0.8    25    92  526.0   6.5   330  53.0  20.9  30.0  法師
2  阿卡莉   125  200   0.0     0    95  575.0   8.0   345  62.4  23.0  37.0  刺客

In [11]:
df2.tail(3)

     名稱  攻擊距離   魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦  類型
144  極靈   550  452   0.8    30    82  504.0   5.5   335  51.6  24.0  30.0  輔助
145  柔依   550  425   0.7    25    92  560.0   6.5   340  58.0  20.8  30.0  法師
146  枷蘿   575  418   0.4    25    79  504.0   5.5   340  53.4  29.0  30.0  法師

In [12]:
df2.describe()

,攻擊距離,魔力,魔力回復,魔力提升,生命提升,生命,生命回復,移動速度,物理攻擊,物理防禦,魔法防禦
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,326.394558,309.659864,0.565306,33.027211,88.523810,555.825170,6.602041,336.312925,59.374830,30.058503,31.131293
std,196.523538,115.398327,0.280570,16.623529,6.651123,37.327458,1.781698,7.560534,6.171353,6.718344,1.707550
min,125.000000,0.000000,0.000000,0.000000,65.000000,340.000000,2.500000,315.000000,40.400000,17.000000,25.000000
25%,125.000000,278.500000,0.400000,25.000000,85.000000,532.400000,5.500000,330.000000,55.000000,24.500000,30.000000
50%,175.000000,325.000000,0.600000,38.000000,89.000000,562.000000,7.000000,335.000000,60.000000,30.000000,32.000000
75%,525.000000,376.000000,0.800000,43.500000,92.000000,582.100000,8.000000,340.000000,64.000000,35.000000,32.100000
max,650.000000,500.000000,1.000000,67.000000,112.000000,625.600000,10.000000,355.000000,70.000000,47.000000,39.000000

In [13]:
numpy_data = df2.values #to numpy

In [14]:
df2.T #transpose

,0,1,2,3,4,5,6,7,8,9,...,137,138,139,140,141,142,143,144,145,146
名稱,厄薩斯,阿璃,阿卡莉,亞歷斯塔,阿姆姆,艾妮維亞,安妮,亞菲利歐,艾希,翱銳龍獸,...,趙信,犽宿,約瑞科,悠咪,札克,劫,希格斯,極靈,柔依,枷蘿
攻擊距離,175,550,125,125,125,600,625,550,600,550,...,175,175,175,500,175,125,550,550,550,575
魔力,0,418,200,350,287,495,418,348,280,350,...,273,100,300,400,0,200,480,452,425,418
魔力回復,0,0.8,0,0.8,0.5,0.8,0.8,0.4,0.4,0.8,...,0.5,0,0.8,0.4,0,0,0.8,0.8,0.7,0.4
魔力提升,0,25,0,40,40,25,25,42,32,50,...,35,0,40,45,0,0,23,30,25,25
生命提升,90,92,95,106,84,82,88,86,85,92,...,92,87,100,70,95,85,92,82,92,79
生命,580,526,575,573.4,613.1,480,524,530,539,575,...,570,523,580,480,615,584,536,504,560,504
生命回復,3,6.5,8,8.5,9,5.5,5.5,3.25,3.5,7,...,8,6.5,8,7,8,7,6.5,5.5,6.5,5.5
移動速度,345,330,345,330,335,325,335,330,325,325,...,345,345,340,330,340,345,325,335,340,340
物理攻擊,60,53,62.4,61.1,53.4,51.4,50.4,57,61,57,...,66,60,62,55,60,63,54.2,51.6,58,53.4
物理防禦,38,20.9,23,44,33,21.2,19.2,28,26,19,...,35,30,39,25,33,32,21.5,24,20.8,29
魔法防禦,32.1,30,37,32.1,32.1,30,30,26,30,30,...,32.1,30,32,25,32,32.1,30,30,30,30
類型,鬥士,法師,刺客,坦克,坦克,法師,法師,射手,射手,法師,...,鬥士,鬥士,鬥士,輔助,坦克,刺客,法師,輔助,法師,法師

# Selection

## Getting

In [15]:
df2['名稱']

0       厄薩斯
1        阿璃
2       阿卡莉
3      亞歷斯塔
4       阿姆姆
       ...
142       劫
143     希格斯
144      極靈
145      柔依
146      枷蘿
Name: 名稱, Length: 147, dtype: object

# Selection by Label

In [16]:
df2.loc[2]

名稱       阿卡莉
攻擊距離     125
魔力       200
魔力回復       0
魔力提升       0
生命提升      95
生命       575
生命回復       8
移動速度     345
物理攻擊    62.4
物理防禦      23
魔法防禦      37
類型        刺客
Name: 2, dtype: object

# Selection by Position

In [17]:
df2.iloc[2]

名稱       阿卡莉
攻擊距離     125
魔力       200
魔力回復       0
魔力提升       0
生命提升      95
生命       575
生命回復       8
移動速度     345
物理攻擊    62.4
物理防禦      23
魔法防禦      37
類型        刺客
Name: 2, dtype: object

In [18]:
df2.iloc[2,0]

'阿卡莉'

In [19]:
df2.iloc[[1, 2, 4], [0, 2]]

    名稱   魔力
1   阿璃  418
2  阿卡莉  200
4  阿姆姆  287

In [20]:
df2.iloc[:,:3]

       名稱  攻擊距離   魔力
0     厄薩斯   175    0
1      阿璃   550  418
2     阿卡莉   125  200
3    亞歷斯塔   125  350
4     阿姆姆   125  287
..    ...   ...  ...
142     劫   125  200
143   希格斯   550  480
144    極靈   550  452
145    柔依   550  425
146    枷蘿   575  418

[147 rows x 3 columns]

# Boolean Indexing

In [21]:
df = df2[df2['魔力提升'] > 0]
df

,名稱,攻擊距離,魔力,魔力回復,魔力提升,生命提升,生命,生命回復,移動速度,物理攻擊,物理防禦,魔法防禦,類型
1,阿璃,550,418,0.8,25,92,526.0,6.5,330,53.0,20.9,30.0,法師
3,亞歷斯塔,125,350,0.8,40,106,573.4,8.5,330,61.1,44.0,32.1,坦克
4,阿姆姆,125,287,0.5,40,84,613.1,9.0,335,53.4,33.0,32.1,坦克
5,艾妮維亞,600,495,0.8,25,82,480.0,5.5,325,51.4,21.2,30.0,法師
6,安妮,625,418,0.8,25,88,524.0,5.5,335,50.4,19.2,30.0,法師
...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,悠咪,500,400,0.4,45,70,480.0,7.0,330,55.0,25.0,25.0,輔助
143,希格斯,550,480,0.8,23,92,536.0,6.5,325,54.2,21.5,30.0,法師
144,極靈,550,452,0.8,30,82,504.0,5.5,335,51.6,24.0,30.0,輔助
145,柔依,550,425,0.7,25,92,560.0,6.5,340,58.0,20.8,30.0,法師
146,枷蘿,575,418,0.4,25,79,504.0,5.5,340,53.4,29.0,30.0,法師

# Missing Data

## drop

In [22]:
df = df2.drop(columns=['名稱', '類型'])
df = df[df > 0]
df

     攻擊距離     魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦
0     175    NaN   NaN   NaN    90  580.0   3.0   345  60.0  38.0  32.1
1     550  418.0   0.8  25.0    92  526.0   6.5   330  53.0  20.9  30.0
2     125  200.0   NaN   NaN    95  575.0   8.0   345  62.4  23.0  37.0
3     125  350.0   0.8  40.0   106  573.4   8.5   330  61.1  44.0  32.1
4     125  287.0   0.5  40.0    84  613.1   9.0   335  53.4  33.0  32.1
..    ...    ...   ...   ...   ...    ...   ...   ...   ...   ...   ...
142   125  200.0   NaN   NaN    85  584.0   7.0   345  63.0  32.0  32.1
143   550  480.0   0.8  23.0    92  536.0   6.5   325  54.2  21.5  30.0
144   550  452.0   0.8  30.0    82  504.0   5.5   335  51.6  24.0  30.0
145   550  425.0   0.7  25.0    92  560.0   6.5   340  58.0  20.8  30.0
146   575  418.0   0.4  25.0    79  504.0   5.5   340  53.4  29.0  30.0

[147 rows x 11 columns]

## dropna

In [23]:
df = df2.drop(columns=['名稱', '類型'])
df = df[df > 0]

df = df.dropna(axis=0,how='any')
df

     攻擊距離     魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦
1     550  418.0   0.8  25.0    92  526.0   6.5   330  53.0  20.9  30.0
3     125  350.0   0.8  40.0   106  573.4   8.5   330  61.1  44.0  32.1
4     125  287.0   0.5  40.0    84  613.1   9.0   335  53.4  33.0  32.1
5     600  495.0   0.8  25.0    82  480.0   5.5   325  51.4  21.2  30.0
6     625  418.0   0.8  25.0    88  524.0   5.5   335  50.4  19.2  30.0
..    ...    ...   ...   ...   ...    ...   ...   ...   ...   ...   ...
140   500  400.0   0.4  45.0    70  480.0   7.0   330  55.0  25.0  25.0
143   550  480.0   0.8  23.0    92  536.0   6.5   325  54.2  21.5  30.0
144   550  452.0   0.8  30.0    82  504.0   5.5   335  51.6  24.0  30.0
145   550  425.0   0.7  25.0    92  560.0   6.5   340  58.0  20.8  30.0
146   575  418.0   0.4  25.0    79  504.0   5.5   340  53.4  29.0  30.0

[125 rows x 11 columns]

In [24]:
df = df2.drop(columns=['名稱', '類型'])
df = df[df > 0]

df = df.dropna(axis=1,how='any')
df

     攻擊距離  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦
0     175    90  580.0   3.0   345  60.0  38.0  32.1
1     550    92  526.0   6.5   330  53.0  20.9  30.0
2     125    95  575.0   8.0   345  62.4  23.0  37.0
3     125   106  573.4   8.5   330  61.1  44.0  32.1
4     125    84  613.1   9.0   335  53.4  33.0  32.1
..    ...   ...    ...   ...   ...   ...   ...   ...
142   125    85  584.0   7.0   345  63.0  32.0  32.1
143   550    92  536.0   6.5   325  54.2  21.5  30.0
144   550    82  504.0   5.5   335  51.6  24.0  30.0
145   550    92  560.0   6.5   340  58.0  20.8  30.0
146   575    79  504.0   5.5   340  53.4  29.0  30.0

[147 rows x 8 columns]

## fillna

In [25]:
df = df2.drop(columns=['名稱', '類型'])
df = df[df > 0]

df = df.fillna(value=5)
df

     攻擊距離     魔力  魔力回復  魔力提升  生命提升     生命  生命回復  移動速度  物理攻擊  物理防禦  魔法防禦
0     175    5.0   5.0   5.0    90  580.0   3.0   345  60.0  38.0  32.1
1     550  418.0   0.8  25.0    92  526.0   6.5   330  53.0  20.9  30.0
2     125  200.0   5.0   5.0    95  575.0   8.0   345  62.4  23.0  37.0
3     125  350.0   0.8  40.0   106  573.4   8.5   330  61.1  44.0  32.1
4     125  287.0   0.5  40.0    84  613.1   9.0   335  53.4  33.0  32.1
..    ...    ...   ...   ...   ...    ...   ...   ...   ...   ...   ...
142   125  200.0   5.0   5.0    85  584.0   7.0   345  63.0  32.0  32.1
143   550  480.0   0.8  23.0    92  536.0   6.5   325  54.2  21.5  30.0
144   550  452.0   0.8  30.0    82  504.0   5.5   335  51.6  24.0  30.0
145   550  425.0   0.7  25.0    92  560.0   6.5   340  58.0  20.8  30.0
146   575  418.0   0.4  25.0    79  504.0   5.5   340  53.4  29.0  30.0

[147 rows x 11 columns]

# Statistic

In [26]:
df2.sum()

名稱      厄薩斯阿璃阿卡莉亞歷斯塔阿姆姆艾妮維亞安妮亞菲利歐艾希翱銳龍獸阿祈爾巴德布里茨布蘭德布郎姆凱...
攻擊距離                                                47980
魔力                                                  45520
魔力回復                                                 83.1
魔力提升                                                 4855
生命提升                                                13013
生命                                                81706.3
生命回復                                                970.5
移動速度                                                49438
物理攻擊                                               8728.1
物理防禦                                               4418.6
魔法防禦                                               4576.3
類型      鬥士法師刺客坦克坦克法師法師射手射手法師法師輔助坦克法師輔助射手鬥士法師坦克射手鬥士鬥士鬥士...
dtype: object

In [27]:
df2.sum(1)

0      1323.1
1      2052.2
2      1470.4
3      1670.9
4      1612.1
        ...
142    1473.1
143    2119.0
144    2064.9
145    2108.0
146    2059.3
Length: 147, dtype: float64

In [28]:
df2.mean()

攻擊距離    326.394558
魔力      309.659864
魔力回復      0.565306
魔力提升     33.027211
生命提升     88.523810
生命      555.825170
生命回復      6.602041
移動速度    336.312925
物理攻擊     59.374830
物理防禦     30.058503
魔法防禦     31.131293
dtype: float64

In [29]:
df2.mean(1)

0      120.281818
1      186.563636
2      133.672727
3      151.900000
4      146.554545
          ...
142    133.918182
143    192.636364
144    187.718182
145    191.636364
146    187.209091
Length: 147, dtype: float64

# Apply

In [30]:
df2['攻擊距離'] = df2['攻擊距離'].apply(lambda x: x/100)
df2

,名稱,攻擊距離,魔力,魔力回復,魔力提升,生命提升,生命,生命回復,移動速度,物理攻擊,物理防禦,魔法防禦,類型
0,厄薩斯,1.75,0,0.0,0,90,580.0,3.0,345,60.0,38.0,32.1,鬥士
1,阿璃,5.50,418,0.8,25,92,526.0,6.5,330,53.0,20.9,30.0,法師
2,阿卡莉,1.25,200,0.0,0,95,575.0,8.0,345,62.4,23.0,37.0,刺客
3,亞歷斯塔,1.25,350,0.8,40,106,573.4,8.5,330,61.1,44.0,32.1,坦克
4,阿姆姆,1.25,287,0.5,40,84,613.1,9.0,335,53.4,33.0,32.1,坦克
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,劫,1.25,200,0.0,0,85,584.0,7.0,345,63.0,32.0,32.1,刺客
143,希格斯,5.50,480,0.8,23,92,536.0,6.5,325,54.2,21.5,30.0,法師
144,極靈,5.50,452,0.8,30,82,504.0,5.5,335,51.6,24.0,30.0,輔助
145,柔依,5.50,425,0.7,25,92,560.0,6.5,340,58.0,20.8,30.0,法師
146,枷蘿,5.75,418,0.4,25,79,504.0,5.5,340,53.4,29.0,30.0,法師

# Grouping

In [31]:
df2.groupby(by='魔力', as_index=False).mean()

,魔力,攻擊距離,魔力回復,魔力提升,生命提升,生命,生命回復,移動速度,物理攻擊,物理防禦,魔法防禦
0,0,1.500000,0.00,0.000000,89.666667,593.000000,6.916667,341.666667,61.550000,33.983333,32.083333
1,2,4.500000,0.00,0.000000,96.000000,537.000000,7.000000,330.000000,55.000000,23.000000,30.000000
2,4,1.250000,0.00,0.000000,90.000000,585.000000,7.000000,345.000000,68.000000,34.000000,32.100000
3,100,1.472222,0.00,0.000000,84.666667,544.733333,6.944444,341.111111,63.777778,34.100000,31.622222
4,200,2.312500,0.00,0.000000,87.250000,568.750000,7.000000,342.500000,60.850000,29.250000,32.800000
...,...,...,...,...,...,...,...,...,...,...,...
63,475,5.500000,0.40,30.000000,90.000000,550.000000,7.000000,325.000000,53.000000,22.000000,30.000000
64,480,5.500000,0.80,28.666667,89.000000,516.333333,6.166667,328.333333,53.866667,21.633333,30.000000
65,490,5.500000,0.80,26.000000,94.000000,505.000000,6.500000,340.000000,50.700000,22.600000,30.000000
66,495,6.000000,0.80,25.000000,82.000000,480.000000,5.500000,325.000000,51.400000,21.200000,30.000000
67,500,3.150000,0.75,34.000000,96.000000,543.200000,6.750000,335.000000,53.700000,27.000000,31.000000